---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-cap-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-cap-green
  template:
    metadata:
      labels:
        app: udacity-cap-green
    spec:
      containers:
      - name: udacity-cap-green
        image: 981422959347.dkr.ecr.us-west-2.amazonaws.com/udacitycap:34
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
