---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-cap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-cap
  template:
    metadata:
      labels:
        app: udacity-cap
    spec:
      containers:
      - name: udacity-cap
        image: IMAGE
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
