---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: udacity-cluster
  region: us-west-2
nodeGroups:
  - name: udacity-workers-green
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
